name: Deploy Functions + Hosting (main)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Firebase CLI
        run: npm i -g firebase-tools
      - name: Install root deps
        run: npm ci
      - name: Install functions deps
        working-directory: functions
        run: npm ci
      - name: Deploy stripeWebhook + hosting
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VETAIDJAMALAI }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > /tmp/sa.json
          firebase deploy --only functions:stripeWebhook,hosting --project vetaidjamalai --token "$(firebase ci:token:fetch --service-account /tmp/sa.json)"
